### ISSUE TITLE
Deploy contracts fails

### ISSUE THREAD

**Issue by MentatX** [hashgraph/hedera-accelerator-defi-dex#632]
### Description

Clone repo and run deployment. 
Result: Fails with an error
Expect: Deploy smart-contract

### Steps to reproduce

```bash
$ git clone https://github.com/hashgraph/hedera-accelerator-defi-dex.git
$ hedera-accelerator-defi-dex/
$ npm i
$ npx hardhat compile
$ npx hardhat run deployment/deploy.ts
```

### Additional context

$ npx hardhat run deployment/deploy.ts
/home/ubuntux/hedera-accelerator-defi-dex/node_modules/@hashgraph/sdk/lib/account/AccountId.cjs:83
    if (text.startsWith("0x") && text.length == 42 || text.length == 40) {
             ^
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Function.fromString (/home/ubuntux/hedera-accelerator-defi-dex/node_modules/@hashgraph/sdk/lib/account/AccountId.cjs:83:14)
    at initClientsInfo (/home/ubuntux/hedera-accelerator-defi-dex/utils/ClientManagement.ts:37:34)
    at Object.<anonymous> (/home/ubuntux/hedera-accelerator-defi-dex/utils/ClientManagement.ts:95:21)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module.m._compile (/home/ubuntux/hedera-accelerator-defi-dex/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ubuntux/hedera-accelerator-defi-dex/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)

### Hedera network

testnet

### Version

Ubuntu 20.04.2 LTS

### Operating system

Linux

**Comment by web3-nomad** [comment]
have you created your .env file ?
```
PROXY_ADMIN_ID=0.0.3418046
PROXY_ADMIN_KEY=xxxx
TREASURE_ID=0.0.2948681
TREASURE_KEY=xxxx
OPERATOR_ID=0.0.3418053
OPERATOR_KEY=xxxx
CHILD_PROXY_ADMIN_ID=0.0.3418051
CHILD_PROXY_ADMIN_KEY=xxxx
OPERATOR_ID_WITH_NO_GOD_TOKEN=0.0.2660920
OPERATOR_KEY_WITH_NO_GOD_TOKEN=xxxx
UI_USER_ID=0.0.3418035
UI_USER_KEY=xxx
```
the KEYs are 0x values from the testnet portal

**Comment by web3-nomad** [comment]
closing due to lack of activity
